<?php

namespace AppBundle\Repository;

/**
 * SystemeventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemeventsRepository extends \Doctrine\ORM\EntityRepository
{
}
