<?php

namespace AppBundle\Entity\Repository;

/**
 * EventMacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventMacRepository extends \Doctrine\ORM\EntityRepository
{
}
